services:
  api:
    build: ./app
    container_name: fase3-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=technova
      - DB_USER=technova
      - DB_PASSWORD=technova
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet
  postgres:
    image: postgres:15-alpine
    container_name: fase3-db
    environment:
      - POSTGRES_DB=technova
      - POSTGRES_USER=technova
      - POSTGRES_PASSWORD=technova
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U technova"]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  appnet:
    driver: bridge
